/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-07-28 03:56:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class in_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/css/inp.css", Long.valueOf(1405929438930L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/css; charset=iso-8859-1\">\r\n");
      out.write("<style type=\"text/css\">");
      out.write("@CHARSET \"ISO-8859-1\";\r\n");
      out.write("#main {\r\n");
      out.write("width:100%;\r\n");
      out.write("height: 600px;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("color:white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first {\r\n");
      out.write("background-image:url(https://biggerthomas.files.wordpress.com/2009/09/fire.jpg);\r\n");
      out.write("background-color: red;\r\n");
      out.write(" padding:40px 0px 40px 0px;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" font-size: 60px;\r\n");
      out.write(" font-family: Blippo, fantasy;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #second {\r\n");
      out.write(" background-color: black;\r\n");
      out.write(" height: 60%;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" color:white;\r\n");
      out.write(" font-size: 20px;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #third {\r\n");
      out.write(" background-color: red;\r\n");
      out.write(" height: 10%;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" font-family: Blippo, fantasy;\r\n");
      out.write(" color: white;\r\n");
      out.write(" font-size: 20px;\r\n");
      out.write(" }");
      out.write("</style>\r\n");
      out.write("<title>sign-in page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id= \"main\">\r\n");
      out.write("\t<div id= \"first\" >\r\n");
      out.write("\t\tWORLD OF <span style=\"color:white\">HELL666</SPAN> WELCOMES YOU!! \r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\t<div id= \"second\">login into hell:\r\n");
      out.write("\t\t<form action=\"/Devil666/signup\" method=\"post\">\r\n");
      out.write("\t\t\t<table align= \"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Sinnername: </th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" name=\"sinnername\" value = \"\"><br></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Password: </th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"password\" name=\"pwd\" value = \"\"><br></th>\t\r\n");
      out.write("\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t<a href=\"file:///C:/Users/user/Desktop/registration_page.html\">NEW-SINNER</a>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id= \"third\">\r\n");
      out.write("\t\t<p> HELL TRADEMARK: ALL RIGHTS RESRVED </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
