/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-07-25 08:03:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/javascript/regist.js", Long.valueOf(1406104871424L));
    _jspx_dependants.put("/WEB-INF/css/reg.css", Long.valueOf(1406100154074L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/css; charset=iso-8859-1\">\r\n");
      out.write("<style type=\"text/css\">");
      out.write("@CHARSET \"ISO-8859-1\";\r\n");
      out.write("#main {\r\n");
      out.write("width:100%;\r\n");
      out.write("height: 600px;\r\n");
      out.write("}\r\n");
      out.write("table: {\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first {\r\n");
      out.write("background-image:url(https://biggerthomas.files.wordpress.com/2009/09/fire.jpg);\r\n");
      out.write("background-color: red;\r\n");
      out.write(" padding:40px 0px 40px 0px;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" font-size: 60px;\r\n");
      out.write(" font-family: Blippo, fantasy;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #second {\r\n");
      out.write(" background-color: black;\r\n");
      out.write(" height: 60%;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" color:white;\r\n");
      out.write(" font-size: 20px;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #third {\r\n");
      out.write(" background-color: red;\r\n");
      out.write(" height: 10%;\r\n");
      out.write(" width:100%;\r\n");
      out.write(" float:left;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" font-family: Blippo, fantasy;\r\n");
      out.write(" color: white;\r\n");
      out.write(" font-size: 20px;\r\n");
      out.write(" }");
      out.write("</style>\r\n");
      out.write("<script>");
      out.write("function validateForm() \r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("    var x = document.forms[\"myForm\"][\"firstname\"];\r\n");
      out.write("\tvar y = document.forms[\"myForm\"][\"lastname\"];\r\n");
      out.write("\tvar z = document.forms[\"myForm\"][\"pwd\"];\r\n");
      out.write("\tvar a = document.forms[\"myForm\"][\"cpwd\"];\r\n");
      out.write("\tvar b = document.forms[\"myForm\"][\"sexm\"];\r\n");
      out.write("\tvar c = document.forms[\"myForm\"][\"sexf\"];\r\n");
      out.write("\tvar d = document.forms[\"myForm\"][\"E-mailid\"];\r\n");
      out.write("\tvar e = document.forms[\"myForm\"][\"vehicle1\"];\r\n");
      out.write("\tvar f = document.forms[\"myForm\"][\"vehicle2\"];\r\n");
      out.write("\tvar g = document.forms[\"myForm\"][\"vehicle3\"];\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar flag = 0;\r\n");
      out.write("\t\r\n");
      out.write("\tif ( (x.value==null || x.value==\"\") && (y.value==null || y.value==\"\") && (z.value==null || z.value==\"\") && (a.value==null || a.value==\"\") \r\n");
      out.write("\t\t&& (b.value==null || b.value==\"\") && (c.value==null || c.value==\"\") && (d.value==null || d.value==\"\") && (e.value==null || e.value==\"\") \r\n");
      out.write("\t\t&& (f.value==null || f.value==\"\") && (g.value==null || g.value==\"\") ) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"All enteries must be filled to be a sinner...\");\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(x.value==null || x.value==\"\")\r\n");
      out.write("\t\t{\t\r\n");
      out.write("\t\t\tx.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(y.value==null || y.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ty.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(z.value==null || z.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tz.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(a.value==null || a.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ta.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(b.value==null || b.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tb.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(c.value==null || c.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tc.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(d.value==null || d.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\td.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(e.value==null || e.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\te.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.value==null || f.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tf.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(g.value==null || g.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tg.parentNode.parentNode.lastElementChild.innerHTML = \"dsfsdfdfsb\";\r\n");
      out.write("\t\t\tflag = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\tif (flag = 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<title>sign-in page</title>\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"\">\r\n");
      out.write("<div id= \"main\">\r\n");
      out.write("\t<div id= \"first\" >\r\n");
      out.write("\t\tWORLD OF <span style=\"color:white\">HELL666</SPAN> WELCOMES YOU!! \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id= \"second\">NEW SINNER SIGNING TO HELL:\r\n");
      out.write("\t\t<form name=\"myForm\"  onsubmit=\"return validateForm()\" action=\"/Devil666/registration\" method= \"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--div style=\"width:600px; float:left;\">\r\n");
      out.write("\t\t\t\t<div style=\"width:100%; float:left;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width:30%; float:left;\"><label for=\"firstname\">First name:</label></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:30%; float:left;\"><input type=\"text\" name=\"firstname\" value= \"\" /></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:30%; float:left;\">sadsad</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table align= \"center\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<td><label for=\"firstname\">First name:</label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"firstname\" value= \"\" /></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"lastname\">Last name: </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"lastname\" value= \"\"><br></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"pwd\">Password: </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"pwd\" value=\"\"><br></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"cpwd\">Confirm Password: </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"cpwd\" value= \"\"><br></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"male\">Gender:</label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"radio\" name=\"sex\" id=\"male\" value=\"male\">male\r\n");
      out.write("\t\t\t\t\t\t<label for=\"female\"></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" id=\"female\" value=\"female\">female<br></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"E-mailid\">E-Mail ID: </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"E-mailid\"><br></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>vehicle:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"vehicle\" value=\"bike\">bike\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"vehicle\" value=\"car\">car\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"vehicle\" value=\"other\">other<br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\" >\r\n");
      out.write("\t\t\t<a href=\"file:///C:/Users/user/Desktop/main_page.html\">back to hell page</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id= \"third\">\r\n");
      out.write("\t\t<p> HELL TRADEMARK: ALL RIGHTS RESRVED </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
